/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Sep 26 16:04:36 2017. */

#include "occulow.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CountMessage_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CountMessage, count_in, count_in, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CountMessage, count_out, count_in, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
