/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Aug 10 17:03:59 2017. */

#include "sensorbug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorMessage_fields[16] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, SensorMessage, pir_status, pir_status, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, SensorMessage, mic, pir_status, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, SensorMessage, light, mic, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, accelx, light, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, accely, accelx, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, accelz, accely, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, gyrx, accelz, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, gyry, gyrx, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, gyrz, gyry, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, magx, gyrz, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, magy, magx, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, magz, magy, 0),
    PB_FIELD( 13, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, temperature, magz, 0),
    PB_FIELD( 14, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, pressure, temperature, 0),
    PB_FIELD( 15, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorMessage, humidity, pressure, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
